(eval-when-compile    (require 'color-theme))
(defun my-color-theme ()
  "Color theme by Eugene Kim, created 2023-07-26."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "unspecified-bg")
      (background-mode . dark)
      (cursor-color . "white")
      (foreground-color . "unspecified-fg"))
     ((ac-fuzzy-cursor-color . "red")
      (buffer-face-mode-face . variable-pitch)
      (compilation-message-face . underline)
      (hl-line-face . hl-line)
      (ibuffer-deletion-face . error)
      (ibuffer-filter-group-name-face . bold)
      (ibuffer-marked-face . warning)
      (ibuffer-title-face . font-lock-type-face)
      (info-lookup-highlight-face . match)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-current-line-face . lazy-highlight)
      (list-matching-lines-face . match)
      (list-matching-lines-prefix-face . shadow)
      (lsp-enable-text-document-color . t)
      (org-cite-basic-mouse-over-key-face . highlight)
      (tags-tag-face . default)
      (widget-mouse-face . highlight))
     (default ((t (:extend nil :stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 1 :width normal :foundry "default" :family "default"))))
     (Info-quoted ((t (:family "Monospace Serif"))))
     (ac-candidate-face ((t (:foreground "black" :background "lightgray" :extend nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1))))
     (ac-candidate-mouse-face ((t (:foreground "white" :background "blue"))))
     (ac-completion-face ((t (:foreground "darkgray" :underline t))))
     (ac-selection-face ((t (:foreground "white" :background "steelblue" :extend nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1))))
     (ansi-color-black ((t (:background "black" :foreground "black"))))
     (ansi-color-blue ((t (:background "blue2" :foreground "blue2"))))
     (ansi-color-bold ((t (:bold t :weight bold))))
     (ansi-color-bright-black ((t (:background "gray30" :foreground "gray30"))))
     (ansi-color-bright-blue ((t (:background "blue1" :foreground "blue1"))))
     (ansi-color-bright-cyan ((t (:background "cyan2" :foreground "cyan2"))))
     (ansi-color-bright-green ((t (:background "green2" :foreground "green2"))))
     (ansi-color-bright-magenta ((t (:background "magenta2" :foreground "magenta2"))))
     (ansi-color-bright-red ((t (:background "red2" :foreground "red2"))))
     (ansi-color-bright-white ((t (:background "white" :foreground "white"))))
     (ansi-color-bright-yellow ((t (:background "yellow2" :foreground "yellow2"))))
     (ansi-color-cyan ((t (:background "cyan3" :foreground "cyan3"))))
     (ansi-color-faint ((t (:weight light))))
     (ansi-color-fast-blink ((t (:box (:line-width -1)))))
     (ansi-color-green ((t (:background "green3" :foreground "green3"))))
     (ansi-color-inverse ((t (nil))))
     (ansi-color-italic ((t (:italic t :slant italic))))
     (ansi-color-magenta ((t (:background "magenta3" :foreground "magenta3"))))
     (ansi-color-red ((t (:background "red3" :foreground "red3"))))
     (ansi-color-slow-blink ((t (:box (:line-width -1)))))
     (ansi-color-underline ((t (:bold t :weight bold))))
     (ansi-color-white ((t (:background "gray90" :foreground "grey90"))))
     (ansi-color-yellow ((t (:background "yellow3" :foreground "yellow3"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (breakpoint-disabled ((t (:foreground "grey70"))))
     (breakpoint-enabled ((t (:bold t :foreground "red1" :weight bold))))
     (browse-url-button ((t (:underline t :foreground "cyan1"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (bui-action-button ((t (nil))))
     (bui-action-button-mouse ((t (nil))))
     (bui-file-name ((t (:underline t :foreground "cyan1"))))
     (bui-hint-key ((t (:bold t :foreground "Pink" :weight bold))))
     (bui-history-button ((t (:foreground "cyan1" :underline t))))
     (bui-info-heading ((t (:bold t :weight bold))))
     (bui-info-param-title ((t (:foreground "PaleGreen"))))
     (bui-time ((t (:foreground "Aquamarine"))))
     (bui-url ((t (:underline t :foreground "cyan1"))))
     (button ((t (:underline t :foreground "cyan1"))))
     (c-annotation-face ((t (:foreground "Aquamarine"))))
     (calendar-month-header ((t (:foreground "LightSkyBlue"))))
     (calendar-today ((t (:underline t))))
     (calendar-weekday-header ((t (:foreground "Aquamarine"))))
     (calendar-weekend-header ((t (:foreground "chocolate1"))))
     (change-log-acknowledgment ((t (:foreground "chocolate1"))))
     (change-log-conditionals ((t (:foreground "LightGoldenrod"))))
     (change-log-date ((t (:foreground "LightSalmon"))))
     (change-log-email ((t (:foreground "LightGoldenrod"))))
     (change-log-file ((t (:foreground "LightSkyBlue"))))
     (change-log-function ((t (:foreground "LightGoldenrod"))))
     (change-log-list ((t (:foreground "Cyan1"))))
     (change-log-name ((t (:foreground "Aquamarine"))))
     (child-frame-border ((t (nil))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan"))))
     (compilation-column-number ((t (:foreground "LightSalmon"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Pink"))))
     (compilation-info ((t (:bold t :weight bold :foreground "Green1"))))
     (compilation-line-number ((t (:foreground "Cyan1"))))
     (compilation-mode-line-exit ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (compilation-mode-line-fail ((t (:bold t :foreground "Red1" :weight bold))))
     (compilation-mode-line-run ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (compilation-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:foreground "lightblue"))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (completions-group-separator ((t (:foreground "grey70" :strike-through t))))
     (completions-group-title ((t (:italic t :foreground "grey70" :slant italic))))
     (cursor ((t (:background "white"))))
     (custom-button ((t (nil))))
     (custom-button-mouse ((t (nil))))
     (custom-button-pressed ((t (nil))))
     (custom-button-pressed-unraised ((t (:bold t :weight bold :foreground "violet"))))
     (custom-button-unraised ((t (:bold t :weight bold))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "yellow3" :foreground "black"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "light blue"))))
     (custom-group-subtitle ((t (:bold t :weight bold))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "light blue" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "pink" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "cyan1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-obsolete ((t (:foreground "light blue"))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "cyan1" :height 0.8))))
     (dap-mouse-eval-thing-face ((t (:background "grey10" :box (:line-width -1 :color "#2aa1ae")))))
     (dap-result-overlay-face ((t (:background "grey10" :box (:line-width -1 :color "black")))))
     (dap-ui-breakpoint-verified-fringe ((t (:bold t :foreground "dark green" :weight bold))))
     (dap-ui-compile-errline ((t (:bold t :foreground "Pink" :weight bold))))
     (dap-ui-locals-scope-face ((t (:bold t :foreground "LightSkyBlue" :underline t :weight bold))))
     (dap-ui-locals-variable-face ((t (:bold t :foreground "LightSteelBlue" :weight bold))))
     (dap-ui-locals-variable-leaf-face ((t (:italic t :foreground "LightSteelBlue" :slant italic))))
     (dap-ui-marker-face ((t (:background "darkolivegreen"))))
     (dap-ui-pending-breakpoint-face ((t (nil))))
     (dap-ui-sessions-active-session-face ((t (:bold t :weight bold))))
     (dap-ui-sessions-running-face ((t (nil))))
     (dap-ui-sessions-stack-frame-face ((t (:foreground "LightSteelBlue"))))
     (dap-ui-sessions-terminated-active-face ((t (:bold t :foreground "grey70" :weight bold))))
     (dap-ui-sessions-terminated-face ((t (:foreground "grey70"))))
     (dap-ui-sessions-thread-active-face ((t (:bold t :weight bold))))
     (dap-ui-sessions-thread-face ((t (nil))))
     (dap-ui-verified-breakpoint-face ((t (nil))))
     (diary ((t (:foreground "yellow1"))))
     (diary-anniversary ((t (:foreground "Cyan1"))))
     (diary-button ((t (nil))))
     (diary-time ((t (:foreground "LightGoldenrod"))))
     (diff-added ((t (:extend t :background "#335533"))))
     (diff-changed ((t (nil))))
     (diff-changed-unspecified ((t (:extend t :background "grey20"))))
     (diff-context ((t (:extend t))))
     (diff-error ((t (:bold t :background "black" :foreground "red" :weight bold))))
     (diff-file-header ((t (:bold t :extend t :background "grey60" :weight bold))))
     (diff-function ((t (:background "grey45" :extend t))))
     (diff-header ((t (:extend t :background "grey45"))))
     (diff-hunk-header ((t (:background "grey45" :extend t))))
     (diff-index ((t (:bold t :weight bold :background "grey60" :extend t))))
     (diff-indicator-added ((t (:background "#335533" :extend t :foreground "#22aa22"))))
     (diff-indicator-changed ((t (:foreground "#aaaa22"))))
     (diff-indicator-removed ((t (:background "#553333" :extend t :foreground "#aa2222"))))
     (diff-nonexistent ((t (:bold t :weight bold :background "grey60" :extend t))))
     (diff-refine-added ((t (:background "#22aa22"))))
     (diff-refine-changed ((t (:background "#aaaa22"))))
     (diff-refine-removed ((t (:background "#aa2222"))))
     (diff-removed ((t (:extend t :background "#553333"))))
     (dired-broken-symlink ((t (:bold t :background "red1" :foreground "yellow1" :weight bold))))
     (dired-directory ((t (:foreground "LightSkyBlue"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Pink"))))
     (dired-header ((t (:foreground "PaleGreen"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-mark ((t (:foreground "Aquamarine"))))
     (dired-marked ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (dired-perm-write ((t (:foreground "chocolate1"))))
     (dired-set-id ((t (:bold t :foreground "Pink" :weight bold))))
     (dired-special ((t (:foreground "LightGoldenrod"))))
     (dired-symlink ((t (:foreground "Cyan1"))))
     (dired-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (dockerfile-image-alias ((t (:foreground "Aquamarine"))))
     (dockerfile-image-name ((t (:foreground "PaleGreen"))))
     (edebug-disabled-breakpoint ((t (:extend t :background "#335533"))))
     (edebug-enabled-breakpoint ((t (:background "darkolivegreen"))))
     (eldoc-highlight-function-argument ((t (:bold t :weight bold))))
     (elisp-shorthand-font-lock-face ((t (:foreground "cyan"))))
     (epa-field-body ((t (:italic t :foreground "turquoise" :slant italic))))
     (epa-field-name ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-mark ((t (:bold t :foreground "orange" :weight bold))))
     (epa-string ((t (:foreground "lightyellow"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :foreground "PaleTurquoise" :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :foreground "PaleTurquoise" :slant italic))))
     (error ((t (:bold t :foreground "Pink" :weight bold))))
     (ert-test-result-expected ((t (:background "green3"))))
     (ert-test-result-unexpected ((t (:background "red3"))))
     (escape-glyph ((t (:foreground "cyan"))))
     (ffap ((t (:background "darkolivegreen"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fill-column-indicator ((t (:foreground "grey70" :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
     (fixed-pitch ((t (:family "Monospace"))))
     (fixed-pitch-serif ((t (:family "Monospace Serif"))))
     (flx-highlight-face ((t (:bold t :foreground "LightGoldenrod" :underline t :weight bold))))
     (flycheck-delimited-error ((t (nil))))
     (flycheck-error ((t (:bold t :weight bold :foreground "Pink" :underline t))))
     (flycheck-error-delimiter ((t (nil))))
     (flycheck-error-list-checker-name ((t (:foreground "LightSkyBlue"))))
     (flycheck-error-list-column-number ((t (nil))))
     (flycheck-error-list-error ((t (:bold t :weight bold :foreground "Pink"))))
     (flycheck-error-list-error-message ((t (nil))))
     (flycheck-error-list-filename ((t (:weight normal))))
     (flycheck-error-list-highlight ((t (:bold t :weight bold))))
     (flycheck-error-list-id ((t (:foreground "PaleGreen"))))
     (flycheck-error-list-id-with-explainer ((t (:foreground "PaleGreen" :box (:style released-button)))))
     (flycheck-error-list-info ((t (:bold t :weight bold :foreground "Green1"))))
     (flycheck-error-list-line-number ((t (nil))))
     (flycheck-error-list-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (flycheck-fringe-error ((t (:bold t :weight bold :foreground "Pink"))))
     (flycheck-fringe-info ((t (:bold t :weight bold :foreground "Green1"))))
     (flycheck-fringe-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (flycheck-info ((t (:bold t :weight bold :foreground "Green1" :underline t))))
     (flycheck-verify-select-checker ((t (:box (:style released-button)))))
     (flycheck-warning ((t (:bold t :weight bold :foreground "DarkOrange" :underline t))))
     (flymake-error ((t (:bold t :weight bold :foreground "Pink"))))
     (flymake-note ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (flymake-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "chocolate1"))))
     (font-lock-comment-face ((t (:foreground "chocolate1"))))
     (font-lock-constant-face ((t (:foreground "Aquamarine"))))
     (font-lock-doc-face ((t (:foreground "LightSalmon"))))
     (font-lock-doc-markup-face ((t (:foreground "Aquamarine"))))
     (font-lock-function-name-face ((t (:foreground "LightSkyBlue"))))
     (font-lock-keyword-face ((t (:foreground "Cyan1"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "LightSalmon"))))
     (font-lock-type-face ((t (:foreground "PaleGreen"))))
     (font-lock-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (font-lock-warning-face ((t (:bold t :weight bold :foreground "Pink"))))
     (fringe ((t (:background "grey10"))))
     (git-commit-comment-action ((t (:bold t :weight bold))))
     (git-commit-comment-branch-local ((t (:foreground "LightGoldenrod"))))
     (git-commit-comment-branch-remote ((t (:foreground "LightGoldenrod"))))
     (git-commit-comment-detached ((t (:foreground "LightGoldenrod"))))
     (git-commit-comment-file ((t (:foreground "LightSalmon"))))
     (git-commit-comment-heading ((t (:foreground "Cyan1"))))
     (git-commit-keyword ((t (:foreground "LightSalmon"))))
     (git-commit-known-pseudo-header ((t (:foreground "Cyan1"))))
     (git-commit-nonempty-second-line ((t (:bold t :foreground "Pink" :weight bold))))
     (git-commit-overlong-summary ((t (:bold t :foreground "Pink" :weight bold))))
     (git-commit-pseudo-header ((t (:foreground "LightSalmon"))))
     (git-commit-summary ((t (:foreground "PaleGreen"))))
     (git-gutter:added ((t (:bold t :family "default" :foundry "default" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "unspecified-bg" :stipple nil :extend nil :foreground "green" :weight bold :height 1))))
     (git-gutter:deleted ((t (:bold t :family "default" :foundry "default" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "unspecified-bg" :stipple nil :extend nil :foreground "red" :weight bold :height 1))))
     (git-gutter:modified ((t (:bold t :family "default" :foundry "default" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "unspecified-bg" :stipple nil :extend nil :foreground "magenta" :weight bold :height 1))))
     (git-gutter:separator ((t (:bold t :family "default" :foundry "default" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :background "unspecified-bg" :stipple nil :extend nil :foreground "cyan" :weight bold :height 1))))
     (git-gutter:unchanged ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :stipple nil :extend nil :background "yellow" :height 1))))
     (glyphless-char ((t (:bold t :weight bold))))
     (header-line ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75" :inverse-video nil :underline t))))
     (header-line-highlight ((t (:background "darkolivegreen"))))
     (helm-M-x-key ((t (:extend t :foreground "orange" :box (:line-width -1)))))
     (helm-M-x-short-doc ((t (:foreground "DimGray" :box (:line-width -1)))))
     (helm-action ((t (:extend t :underline t))))
     (helm-ag-edit-deleted-line ((t (:foreground "chocolate1" :strike-through t))))
     (helm-buffer-archive ((t (:extend t :foreground "Gold"))))
     (helm-buffer-directory ((t (:extend t :background "LightGray" :foreground "DarkRed"))))
     (helm-buffer-file ((t (:foreground "LightSteelBlue" :extend t))))
     (helm-buffer-modified ((t (:foreground "chocolate1" :extend t))))
     (helm-buffer-not-saved ((t (:extend t :foreground "Indianred2"))))
     (helm-buffer-process ((t (:extend t :foreground "Sienna3"))))
     (helm-buffer-saved-out ((t (:extend t :background "black" :foreground "red"))))
     (helm-buffer-size ((t (:extend t :foreground "RosyBrown"))))
     (helm-candidate-number ((t (:extend t :background "Yellow" :foreground "black"))))
     (helm-candidate-number-suspended ((t (:background "black" :foreground "Yellow" :extend t))))
     (helm-command-active-mode ((t (:foreground "LightSteelBlue"))))
     (helm-delete-async-message ((t (:extend t :foreground "yellow"))))
     (helm-eob-line ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend t :height 1))))
     (helm-etags-file ((t (:extend t :foreground "Lightgoldenrod4" :underline t))))
     (helm-ff-backup-file ((t (:extend t :foreground "DimGray"))))
     (helm-ff-denied ((t (:extend t :background "black" :foreground "red"))))
     (helm-ff-directory ((t (:extend t :background "LightGray" :foreground "DarkRed"))))
     (helm-ff-dirs ((t (:foreground "LightSkyBlue" :extend t))))
     (helm-ff-dotted-directory ((t (:extend t :background "DimGray" :foreground "black"))))
     (helm-ff-dotted-symlink-directory ((t (:extend t :background "DimGray" :foreground "DarkOrange"))))
     (helm-ff-executable ((t (:extend t :foreground "green"))))
     (helm-ff-file ((t (:foreground "LightSteelBlue" :extend t))))
     (helm-ff-file-extension ((t (:extend t :foreground "magenta"))))
     (helm-ff-invalid-symlink ((t (:extend t :background "red" :foreground "black"))))
     (helm-ff-nofile ((t (:foreground "LightSteelBlue" :extend t))))
     (helm-ff-pipe ((t (:extend t :background "black" :foreground "yellow"))))
     (helm-ff-prefix ((t (:extend t :background "yellow" :foreground "black"))))
     (helm-ff-rsync-progress ((t (:bold t :foreground "Pink" :weight bold :extend t))))
     (helm-ff-socket ((t (:extend t :foreground "DeepPink"))))
     (helm-ff-suid ((t (:extend t :background "red" :foreground "white"))))
     (helm-ff-symlink ((t (:foreground "chocolate1" :extend t))))
     (helm-ff-truename ((t (:foreground "LightSalmon" :extend t))))
     (helm-grep-cmd-line ((t (:foreground "PaleGreen" :extend t))))
     (helm-grep-file ((t (:extend t :foreground "green" :underline t))))
     (helm-grep-finish ((t (:extend t :foreground "Green"))))
     (helm-grep-lineno ((t (:extend t :foreground "Darkorange1"))))
     (helm-grep-match ((t (:extend t :foreground "gold1"))))
     (helm-header ((t (:underline t :inverse-video nil :background "grey75" :foreground "black" :box (:line-width -1 :style released-button) :extend t))))
     (helm-header-line-left-margin ((t (:extend t :background "yellow" :foreground "black"))))
     (helm-helper ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75" :inverse-video nil :underline t :extend t))))
     (helm-history-deleted ((t (:foreground "black" :background "red" :extend t))))
     (helm-history-remote ((t (:extend t :foreground "Indianred1"))))
     (helm-lisp-completion-info ((t (:extend t :foreground "red"))))
     (helm-lisp-show-completion ((t (:extend t :background "DarkSlateGray"))))
     (helm-locate-finish ((t (:extend t :foreground "Green"))))
     (helm-ls-git-added-copied-face ((t (:foreground "green"))))
     (helm-ls-git-added-modified-face ((t (:foreground "LightSkyBlue"))))
     (helm-ls-git-branches-current ((t (:foreground "gold"))))
     (helm-ls-git-branches-name ((t (:foreground "red"))))
     (helm-ls-git-branches-name-current ((t (:foreground "green"))))
     (helm-ls-git-conflict-face ((t (:foreground "MediumVioletRed"))))
     (helm-ls-git-deleted-and-staged-face ((t (:foreground "DimGray"))))
     (helm-ls-git-deleted-not-staged-face ((t (:foreground "DarkGoldenrod3"))))
     (helm-ls-git-modified-and-staged-face ((t (:foreground "goldenrod"))))
     (helm-ls-git-modified-not-staged-face ((t (:foreground "orange"))))
     (helm-ls-git-renamed-modified-face ((t (:foreground "goldenrod"))))
     (helm-ls-git-untracked-face ((t (:foreground "red"))))
     (helm-mark-prefix ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (helm-match ((t (:extend t :foreground "gold1"))))
     (helm-match-item ((t (:foreground "brown4" :background "palevioletred2" :extend t))))
     (helm-minibuffer-prompt ((t (:foreground "cyan" :extend t))))
     (helm-moccur-buffer ((t (:extend t :foreground "DarkTurquoise" :underline t))))
     (helm-mode-prefix ((t (:extend t))))
     (helm-no-file-buffer-modified ((t (:extend t :background "black" :foreground "orange"))))
     (helm-non-file-buffer ((t (:italic t :slant italic :extend t))))
     (helm-prefarg ((t (:extend t :foreground "green"))))
     (helm-resume-need-update ((t (:extend t :background "red"))))
     (helm-selection ((t (:extend t :background "blue" :foreground "white"))))
     (helm-selection-line ((t (:background "darkolivegreen" :extend t :distant-foreground "black"))))
     (helm-separator ((t (:extend t :foreground "red"))))
     (helm-source-header ((t (:bold t :extend t :background "#22083397778B" :foreground "white" :weight bold :height 1.3 :family "Sans Serif"))))
     (helm-swoop-line-number-face ((t (:foreground "#999999"))))
     (helm-swoop-target-line-block-face ((t (:background "#cccc00" :foreground "#222222"))))
     (helm-swoop-target-line-face ((t (:background "#e3e300" :foreground "#222222"))))
     (helm-swoop-target-word-face ((t (:background "#7700ff" :foreground "#ffffff"))))
     (helm-time-zone-current ((t (:extend t :foreground "green"))))
     (helm-time-zone-home ((t (:extend t :foreground "red"))))
     (helm-visible-mark ((t (:extend t :background "green1" :foreground "black"))))
     (help-argument-name ((t (:italic t :slant italic))))
     (help-for-help-header ((t (:height 1.26))))
     (help-key-binding ((t (:background "grey19" :foreground "LightBlue" :box (:line-width (1 . -1) :color "grey35")))))
     (highlight ((t (:background "darkolivegreen"))))
     (hl-line ((t (:background "darkolivegreen" :extend t))))
     (holiday ((t (:background "chocolate4"))))
     (homoglyph ((t (:foreground "cyan"))))
     (hydra-face-amaranth ((t (:bold t :foreground "#E52B50" :weight bold))))
     (hydra-face-blue ((t (:bold t :foreground "#8ac6f2" :weight bold))))
     (hydra-face-pink ((t (:bold t :foreground "#FF6EB4" :weight bold))))
     (hydra-face-red ((t (:bold t :foreground "#FF0000" :weight bold))))
     (hydra-face-teal ((t (:bold t :foreground "#367588" :weight bold))))
     (ibuffer-locked-buffer ((t (:foreground "RosyBrown"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :foreground "Pink" :weight bold))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:foreground "red1"))))
     (ido-virtual ((t (:foreground "LightSteelBlue"))))
     (image-dired-thumb-mark ((t (:background "orange"))))
     (info-header-node ((t (:italic t :bold t :weight bold :slant italic :foreground "white"))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-index-match ((t (:background "RoyalBlue3"))))
     (info-menu-header ((t (:bold t :underline t :weight bold))))
     (info-menu-star ((t (:foreground "red1"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-title-1 ((t (:bold t :foreground "yellow" :weight bold))))
     (info-title-2 ((t (:bold t :foreground "lightblue" :weight bold))))
     (info-title-3 ((t (:bold t :weight bold))))
     (info-title-4 ((t (:bold t :weight bold))))
     (info-xref ((t (:underline t :foreground "cyan1"))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (internal-border ((t (nil))))
     (isearch ((t (:background "palevioletred2" :foreground "brown4"))))
     (isearch-fail ((t (:background "red4"))))
     (isearch-group-1 ((t (:background "palevioletred1" :foreground "brown4"))))
     (isearch-group-2 ((t (:background "palevioletred3" :foreground "brown4"))))
     (italic ((t (:italic t :slant italic))))
     (ivy-action ((t (:foreground "LightSteelBlue"))))
     (ivy-completions-annotations ((t (:italic t :slant italic))))
     (ivy-confirm-face ((t (:foreground "ForestGreen"))))
     (ivy-current-match ((t (:extend t :background "#65a7e2" :foreground "black"))))
     (ivy-cursor ((t (:background "white" :foreground "black"))))
     (ivy-grep-info ((t (:bold t :foreground "Green1" :weight bold))))
     (ivy-grep-line-number ((t (:foreground "Cyan1"))))
     (ivy-highlight-face ((t (:background "darkolivegreen"))))
     (ivy-match-required-face ((t (:foreground "red"))))
     (ivy-minibuffer-match-face-1 ((t (:background "#555555"))))
     (ivy-minibuffer-match-face-2 ((t (:bold t :background "#777777" :weight bold))))
     (ivy-minibuffer-match-face-3 ((t (:bold t :background "#7777ff" :weight bold))))
     (ivy-minibuffer-match-face-4 ((t (:bold t :background "#8a498a" :weight bold))))
     (ivy-minibuffer-match-highlight ((t (:background "darkolivegreen"))))
     (ivy-modified-buffer ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (ivy-modified-outside-buffer ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (ivy-org ((t (:foreground "chocolate1"))))
     (ivy-prompt-match ((t (:foreground "black" :background "#65a7e2" :extend t))))
     (ivy-remote ((t (:foreground "#7B6BFF"))))
     (ivy-separator ((t (:foreground "LightSalmon"))))
     (ivy-subdir ((t (:foreground "LightSkyBlue"))))
     (ivy-virtual ((t (:foreground "LightSteelBlue"))))
     (ivy-yanked-word ((t (:background "darkolivegreen"))))
     (js2-error ((t (:foreground "red"))))
     (js2-external-variable ((t (:foreground "red"))))
     (js2-function-call ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (js2-function-param ((t (:foreground "SeaGreen"))))
     (js2-instance-member ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter ((t (:foreground "green"))))
     (js2-jsdoc-html-tag-name ((t (:foreground "yellow"))))
     (js2-jsdoc-tag ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value ((t (:foreground "PeachPuff3"))))
     (js2-object-property ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (js2-object-property-access ((t (:extend nil :stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1))))
     (js2-private-function-call ((t (:foreground "goldenrod"))))
     (js2-private-member ((t (:foreground "PeachPuff3"))))
     (js2-warning ((t (:underline "orange"))))
     (jupyter-eval-overlay ((t (:bold t :foreground "dodger blue" :weight bold))))
     (jupyter-repl-input-prompt ((t (:foreground "darkolivegreen"))))
     (jupyter-repl-output-prompt ((t (:foreground "darkred"))))
     (jupyter-repl-traceback ((t (:background "firebrick"))))
     (lazy-highlight ((t (:background "paleturquoise4"))))
     (line-number ((t (:foreground "grey70"))))
     (line-number-current-line ((t (:foreground "grey70"))))
     (line-number-major-tick ((t (:bold t :background "grey75" :weight bold))))
     (line-number-minor-tick ((t (:bold t :background "grey55" :weight bold))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:underline t :foreground "violet"))))
     (log-edit-header ((t (:foreground "Cyan1"))))
     (log-edit-summary ((t (:foreground "LightSkyBlue"))))
     (log-edit-unknown-header ((t (:foreground "chocolate1"))))
     (lsp-details-face ((t (:foreground "grey70" :height 0.8))))
     (lsp-face-highlight-read ((t (:background "darkolivegreen" :underline t))))
     (lsp-face-highlight-textual ((t (:background "darkolivegreen"))))
     (lsp-face-highlight-write ((t (:bold t :background "darkolivegreen" :weight bold))))
     (lsp-face-rename ((t (:underline t))))
     (lsp-inlay-hint-face ((t (:foreground "chocolate1"))))
     (lsp-inlay-hint-parameter-face ((t (:foreground "chocolate1"))))
     (lsp-inlay-hint-type-face ((t (:foreground "chocolate1"))))
     (lsp-installation-buffer-face ((t (:foreground "green"))))
     (lsp-installation-finished-buffer-face ((t (:foreground "orange"))))
     (lsp-lens-face ((t (:foreground "grey70" :height 0.8))))
     (lsp-lens-mouse-face ((t (:underline t :foreground "cyan1" :height 0.8))))
     (lsp-rename-placeholder-face ((t (:foreground "LightGoldenrod"))))
     (lsp-signature-face ((t (:foreground "grey70" :height 0.8))))
     (lsp-signature-posframe ((t (:foreground "black" :background "lightyellow" :family "Sans Serif"))))
     (lsp-treemacs-file-error ((t (:bold t :weight bold :foreground "Pink"))))
     (lsp-treemacs-file-hint ((t (:bold t :weight bold :foreground "Green1"))))
     (lsp-treemacs-file-info ((t (:bold t :weight bold :foreground "Green1"))))
     (lsp-treemacs-file-warn ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (lsp-treemacs-project-root-error ((t (:foreground "Cyan1"))))
     (lsp-treemacs-project-root-info ((t (:foreground "Cyan1"))))
     (lsp-treemacs-project-root-warn ((t (:foreground "Cyan1"))))
     (lv-separator ((t (:background "grey30"))))
     (magit-bisect-bad ((t (:foreground "IndianRed4"))))
     (magit-bisect-good ((t (:foreground "DarkOliveGreen"))))
     (magit-bisect-skip ((t (:foreground "DarkGoldenrod"))))
     (magit-blame-date ((t (nil))))
     (magit-blame-dimmed ((t (:foreground "grey50" :slant normal :weight normal))))
     (magit-blame-hash ((t (nil))))
     (magit-blame-heading ((t (:foreground "white" :background "grey25" :extend t :slant normal :weight normal))))
     (magit-blame-highlight ((t (:extend t :background "grey25" :foreground "white"))))
     (magit-blame-margin ((t (:foreground "white" :background "grey25" :extend t :slant normal :weight normal))))
     (magit-blame-name ((t (nil))))
     (magit-blame-summary ((t (nil))))
     (magit-branch-current ((t (:background "LightSkyBlue1"))))
     (magit-branch-local ((t (:foreground "LightSkyBlue1"))))
     (magit-branch-remote ((t (:foreground "DarkSeaGreen2"))))
     (magit-branch-remote-head ((t (:background "DarkSeaGreen2"))))
     (magit-branch-upstream ((t (:italic t :slant italic))))
     (magit-branch-warning ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (magit-cherry-equivalent ((t (:foreground "magenta"))))
     (magit-cherry-unmatched ((t (:foreground "cyan"))))
     (magit-diff-added ((t (:extend t :background "green" :foreground "black"))))
     (magit-diff-added-highlight ((t (:extend t :background "green" :foreground "black"))))
     (magit-diff-base ((t (:extend t :background "#555522" :foreground "#ffffcc"))))
     (magit-diff-base-highlight ((t (:extend t :background "#666622" :foreground "#eeeebb"))))
     (magit-diff-conflict-heading ((t (:foreground "grey95" :background "grey25" :extend t))))
     (magit-diff-context ((t (:extend t :foreground "grey70"))))
     (magit-diff-context-highlight ((t (:extend t :background "grey20" :foreground "grey70"))))
     (magit-diff-file-heading ((t (:bold t :extend t :weight bold))))
     (magit-diff-file-heading-highlight ((t (:background "grey20" :extend t))))
     (magit-diff-file-heading-selection ((t (:background "grey20" :extend t :foreground "LightSalmon3"))))
     (magit-diff-hunk-heading ((t (:extend t :background "grey25" :foreground "grey95"))))
     (magit-diff-hunk-heading-highlight ((t (:extend t :background "grey35" :foreground "grey95"))))
     (magit-diff-hunk-heading-selection ((t (:background "grey35" :extend t :foreground "LightSalmon3"))))
     (magit-diff-hunk-region ((t (:bold t :weight bold :extend t))))
     (magit-diff-lines-boundary ((t (:foreground "grey80" :background "salmon4" :extend t))))
     (magit-diff-lines-heading ((t (:extend t :background "salmon4" :foreground "grey80"))))
     (magit-diff-our ((t (:foreground "#ffdddd" :background "#553333" :extend t))))
     (magit-diff-our-highlight ((t (:foreground "#eecccc" :background "#663333" :extend t))))
     (magit-diff-removed ((t (:extend t :background "#553333" :foreground "#ffdddd"))))
     (magit-diff-removed-highlight ((t (:extend t :background "#663333" :foreground "#eecccc"))))
     (magit-diff-revision-summary ((t (:foreground "grey95" :background "grey25" :extend t))))
     (magit-diff-revision-summary-highlight ((t (:foreground "grey95" :background "grey35" :extend t))))
     (magit-diff-their ((t (:foreground "black" :background "green" :extend t))))
     (magit-diff-their-highlight ((t (:foreground "black" :background "green" :extend t))))
     (magit-diff-whitespace-warning ((t (:background "red1"))))
     (magit-diffstat-added ((t (:foreground "#448844"))))
     (magit-diffstat-removed ((t (:foreground "#aa4444"))))
     (magit-dimmed ((t (:foreground "grey50"))))
     (magit-filename ((t (:weight normal))))
     (magit-hash ((t (:foreground "white"))))
     (magit-head ((t (:foreground "LightSkyBlue1"))))
     (magit-header-line ((t (:bold t :weight bold :foreground "LightGoldenrod2" :extend t))))
     (magit-header-line-key ((t (:foreground "LightSteelBlue"))))
     (magit-header-line-log-select ((t (:bold t :weight bold))))
     (magit-keyword ((t (:foreground "LightSalmon"))))
     (magit-keyword-squash ((t (:bold t :foreground "Pink" :weight bold))))
     (magit-log-author ((t (:foreground "tomato" :slant normal :weight normal))))
     (magit-log-date ((t (:foreground "grey80" :slant normal :weight normal))))
     (magit-log-graph ((t (:foreground "grey80"))))
     (magit-mode-line-process ((t (:bold t :weight bold))))
     (magit-mode-line-process-error ((t (:bold t :weight bold :foreground "Pink"))))
     (magit-process-ng ((t (:bold t :weight bold :extend t :foreground "red"))))
     (magit-process-ok ((t (:bold t :weight bold :extend t :foreground "green"))))
     (magit-reflog-amend ((t (:foreground "magenta"))))
     (magit-reflog-checkout ((t (:foreground "blue"))))
     (magit-reflog-cherry-pick ((t (:foreground "green"))))
     (magit-reflog-commit ((t (:foreground "green"))))
     (magit-reflog-merge ((t (:foreground "green"))))
     (magit-reflog-other ((t (:foreground "cyan"))))
     (magit-reflog-rebase ((t (:foreground "magenta"))))
     (magit-reflog-remote ((t (:foreground "cyan"))))
     (magit-reflog-reset ((t (:foreground "red"))))
     (magit-refname ((t (:foreground "grey80"))))
     (magit-refname-pullreq ((t (:foreground "grey80"))))
     (magit-refname-stash ((t (:foreground "grey80"))))
     (magit-refname-wip ((t (:foreground "grey80"))))
     (magit-section-child-count ((t (nil))))
     (magit-section-heading ((t (:bold t :extend t :foreground "LightGoldenrod2" :weight bold))))
     (magit-section-heading-selection ((t (:extend t :foreground "LightSalmon3"))))
     (magit-section-highlight ((t (:extend t :background "grey20"))))
     (magit-section-secondary-heading ((t (:bold t :extend t :weight bold))))
     (magit-sequence-done ((t (:foreground "white"))))
     (magit-sequence-drop ((t (:foreground "IndianRed"))))
     (magit-sequence-exec ((t (:foreground "white"))))
     (magit-sequence-head ((t (:foreground "LightSkyBlue1"))))
     (magit-sequence-onto ((t (:foreground "white"))))
     (magit-sequence-part ((t (:foreground "LightGoldenrod2"))))
     (magit-sequence-pick ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (magit-sequence-stop ((t (:foreground "DarkSeaGreen2"))))
     (magit-signature-bad ((t (:bold t :foreground "red" :weight bold))))
     (magit-signature-error ((t (:foreground "light blue"))))
     (magit-signature-expired ((t (:foreground "orange"))))
     (magit-signature-expired-key ((t (:foreground "orange"))))
     (magit-signature-good ((t (:foreground "green"))))
     (magit-signature-revoked ((t (:foreground "violet red"))))
     (magit-signature-untrusted ((t (:foreground "medium aquamarine"))))
     (magit-tag ((t (:foreground "LightGoldenrod2"))))
     (markdown-blockquote-face ((t (:foreground "LightSalmon"))))
     (markdown-bold-face ((t (:bold t :weight bold))))
     (markdown-code-face ((t (:family "Monospace"))))
     (markdown-comment-face ((t (:foreground "chocolate1"))))
     (markdown-footnote-marker-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-footnote-text-face ((t (:foreground "chocolate1"))))
     (markdown-gfm-checkbox-face ((t (:foreground "LightSteelBlue"))))
     (markdown-header-delimiter-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-header-face ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (markdown-header-face-1 ((t (:bold t :weight bold :foreground "LightSkyBlue" :height 1.0))))
     (markdown-header-face-2 ((t (:bold t :weight bold :foreground "LightSkyBlue" :height 1.0))))
     (markdown-header-face-3 ((t (:bold t :weight bold :foreground "LightSkyBlue" :height 1.0))))
     (markdown-header-face-4 ((t (:bold t :weight bold :foreground "LightSkyBlue" :height 1.0))))
     (markdown-header-face-5 ((t (:bold t :weight bold :foreground "LightSkyBlue" :height 1.0))))
     (markdown-header-face-6 ((t (:bold t :weight bold :foreground "LightSkyBlue" :height 1.0))))
     (markdown-header-rule-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-highlight-face ((t (:background "darkolivegreen"))))
     (markdown-highlighting-face ((t (:background "yellow" :foreground "black"))))
     (markdown-hr-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-html-attr-name-face ((t (:foreground "LightGoldenrod"))))
     (markdown-html-attr-value-face ((t (:foreground "LightSalmon"))))
     (markdown-html-entity-face ((t (:foreground "LightGoldenrod"))))
     (markdown-html-tag-delimiter-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-html-tag-name-face ((t (:foreground "PaleGreen"))))
     (markdown-inline-code-face ((t (:family "Monospace"))))
     (markdown-italic-face ((t (:italic t :slant italic))))
     (markdown-language-info-face ((t (:foreground "LightSalmon"))))
     (markdown-language-keyword-face ((t (:foreground "PaleGreen"))))
     (markdown-line-break-face ((t (:foreground "Aquamarine" :underline t))))
     (markdown-link-face ((t (:underline t :foreground "cyan1"))))
     (markdown-link-title-face ((t (:foreground "chocolate1"))))
     (markdown-list-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-markup-face ((t (:foreground "grey70" :slant normal :weight normal))))
     (markdown-math-face ((t (:foreground "LightSalmon"))))
     (markdown-metadata-key-face ((t (:foreground "LightGoldenrod"))))
     (markdown-metadata-value-face ((t (:foreground "LightSalmon"))))
     (markdown-missing-link-face ((t (:bold t :foreground "Pink" :weight bold))))
     (markdown-plain-url-face ((t (:foreground "cyan1" :underline t))))
     (markdown-pre-face ((t (:family "Monospace"))))
     (markdown-reference-face ((t (:weight normal :slant normal :foreground "grey70"))))
     (markdown-strike-through-face ((t (:strike-through t))))
     (markdown-table-face ((t (:family "Monospace"))))
     (markdown-url-face ((t (:foreground "LightSalmon"))))
     (match ((t (:background "RoyalBlue3"))))
     (menu ((t (nil))))
     (message-cited-text-1 ((t (:foreground "LightPink1"))))
     (message-cited-text-2 ((t (:foreground "forest green"))))
     (message-cited-text-3 ((t (:foreground "goldenrod3"))))
     (message-cited-text-4 ((t (:foreground "chocolate3"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (message-signature-separator ((t (:bold t :weight bold))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (mm-command-output ((t (:foreground "ForestGreen"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:background "darkolivegreen"))))
     (mode-line-inactive ((t (:background "grey30" :foreground "grey80" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mouse ((t (nil))))
     (mouse-drag-and-drop-region ((t (:background "blue3" :extend t))))
     (next-error ((t (:background "blue3" :extend t))))
     (next-error-message ((t (:background "darkolivegreen" :extend t))))
     (nobreak-hyphen ((t (:foreground "cyan"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (ns-working-text-face ((t (:underline t))))
     (org-agenda-calendar-event ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (org-agenda-calendar-sexp ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (org-agenda-clocking ((t (:background "SkyBlue4" :extend t))))
     (org-agenda-column-dateline ((t (:weight normal :slant normal :underline nil :strike-through nil :background "grey30"))))
     (org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
     (org-agenda-date ((t (:foreground "LightSkyBlue"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "LightSkyBlue" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "LightSkyBlue" :weight bold))))
     (org-agenda-date-weekend-today ((t (:italic t :bold t :weight bold :slant italic :foreground "LightSkyBlue"))))
     (org-agenda-diary ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-filter-category ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-effort ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-regexp ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-filter-tags ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-agenda-restriction-lock ((t (:background "#1C1C1C"))))
     (org-agenda-structure ((t (:foreground "LightSkyBlue"))))
     (org-agenda-structure-filter ((t (:bold t :weight bold :foreground "Pink"))))
     (org-agenda-structure-secondary ((t (:foreground "LightSkyBlue"))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:family "Monospace" :extend t))))
     (org-block-begin-line ((t (:family "Monospace"))))
     (org-block-end-line ((t (:family "Monospace"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "PaleGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Pink"))))
     (org-cite ((t (:underline t :foreground "cyan1"))))
     (org-cite-key ((t (:underline t :foreground "cyan1"))))
     (org-clock-overlay ((t (:background "SkyBlue4" :foreground "white"))))
     (org-code ((t (:family "Monospace"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:family "Monospace" :foreground "Cyan" :underline t))))
     (org-date-selected ((t (:background "Pink"))))
     (org-default ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (org-dispatcher-highlight ((t (:bold t :background "gray20" :foreground "gold1" :weight bold))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold))))
     (org-done ((t (:bold t :foreground "PaleGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Cyan" :underline t))))
     (org-formula ((t (:family "Monospace" :foreground "chocolate1"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-headline-todo ((t (:foreground "Pink2"))))
     (org-hide ((t (:family "Monospace" :foreground "black"))))
     (org-imminent-deadline ((t (:bold t :weight bold :foreground "Pink"))))
     (org-latex-and-related ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:foreground "LightSkyBlue"))))
     (org-level-2 ((t (:foreground "LightGoldenrod"))))
     (org-level-3 ((t (:foreground "Cyan1"))))
     (org-level-4 ((t (:foreground "chocolate1"))))
     (org-level-5 ((t (:foreground "PaleGreen"))))
     (org-level-6 ((t (:foreground "Aquamarine"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "LightSalmon"))))
     (org-link ((t (:underline t :foreground "cyan1"))))
     (org-list-dt ((t (:bold t :weight bold))))
     (org-macro ((t (:foreground "burlywood"))))
     (org-meta-line ((t (:family "Monospace"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "grey75"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "red"))))
     (org-priority ((t (:foreground "Cyan1"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:extend t :family "Monospace"))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "Cyan1"))))
     (org-table ((t (:family "Monospace" :foreground "LightSkyBlue"))))
     (org-table-header ((t (:family "Monospace" :background "LightGray" :foreground "Black"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-tag-group ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Pink" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-upcoming-distant-deadline ((t (:extend nil :stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1))))
     (org-verbatim ((t (:family "Monospace"))))
     (org-verse ((t (:extend t :family "Monospace"))))
     (org-warning ((t (:bold t :foreground "Pink" :weight bold))))
     (outline-1 ((t (:foreground "LightSkyBlue"))))
     (outline-2 ((t (:foreground "LightGoldenrod"))))
     (outline-3 ((t (:foreground "Cyan1"))))
     (outline-4 ((t (:foreground "chocolate1"))))
     (outline-5 ((t (:foreground "PaleGreen"))))
     (outline-6 ((t (:foreground "Aquamarine"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "LightSalmon"))))
     (package-description ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (package-help-section-name ((t (:bold t :weight bold))))
     (package-name ((t (:underline t :foreground "cyan1"))))
     (package-status-avail-obso ((t (:bold t :foreground "Pink" :weight bold))))
     (package-status-available ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (package-status-built-in ((t (:foreground "LightSteelBlue"))))
     (package-status-dependency ((t (:foreground "chocolate1"))))
     (package-status-disabled ((t (:bold t :foreground "Pink" :weight bold))))
     (package-status-external ((t (:foreground "LightSteelBlue"))))
     (package-status-held ((t (:foreground "Aquamarine"))))
     (package-status-incompat ((t (:bold t :weight bold :foreground "Pink"))))
     (package-status-installed ((t (:foreground "chocolate1"))))
     (package-status-new ((t (:bold t :weight bold))))
     (package-status-unsigned ((t (:bold t :foreground "Pink" :weight bold))))
     (popup-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :extend nil :background "lightgray" :foreground "black" :height 1))))
     (popup-isearch-match ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :stipple nil :extend nil :background "sky blue" :height 1))))
     (popup-menu-face ((t (:foreground "black" :background "lightgray" :extend nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1))))
     (popup-menu-mouse-face ((t (:background "blue" :foreground "white"))))
     (popup-menu-selection-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :extend nil :background "steelblue" :foreground "white" :height 1))))
     (popup-menu-summary-face ((t (:foreground "dimgray" :family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :stipple nil :extend nil :background "lightgray" :height 1))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-summary-face ((t (:background "lightgray" :extend nil :stipple nil :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :foreground "dimgray" :height 1))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (py-XXX-tag-face ((t (:foreground "LightSalmon"))))
     (py-builtins-face ((t (:foreground "LightSteelBlue"))))
     (py-class-name-face ((t (:foreground "PaleGreen"))))
     (py-decorators-face ((t (:foreground "Cyan1"))))
     (py-def-class-face ((t (:foreground "Cyan1"))))
     (py-def-face ((t (:foreground "LightSkyBlue"))))
     (py-exception-name-face ((t (:foreground "LightSteelBlue"))))
     (py-import-from-face ((t (:foreground "Cyan1"))))
     (py-number-face ((t (nil))))
     (py-object-reference-face ((t (:foreground "Cyan1"))))
     (py-pseudo-keyword-face ((t (:foreground "Cyan1"))))
     (py-try-if-face ((t (:foreground "Cyan1"))))
     (py-variable-name-face ((t (:foreground "LightGoldenrod"))))
     (query-replace ((t (:foreground "brown4" :background "palevioletred2"))))
     (read-multiple-choice-face ((t (:bold t :weight bold))))
     (region ((t (:extend t :background "blue3"))))
     (rjsx-attr ((t (:foreground "LightGoldenrod"))))
     (rjsx-tag ((t (:foreground "LightSkyBlue"))))
     (rjsx-tag-bracket-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (rjsx-text ((t (:foreground "LightSalmon"))))
     (rmail-header-name ((t (:foreground "LightSkyBlue"))))
     (rmail-highlight ((t (:background "darkolivegreen"))))
     (scroll-bar ((t (:foreground "white"))))
     (secondary-selection ((t (:extend t :background "SkyBlue4"))))
     (separator-line ((t (:foreground "ForestGreen"))))
     (sgml-namespace ((t (:foreground "LightSteelBlue"))))
     (sh-escaped-newline ((t (:foreground "LightSalmon"))))
     (sh-heredoc ((t (:bold t :foreground "yellow1" :weight bold))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (shortdoc-heading ((t (:bold t :family "Sans Serif" :weight bold :height 1.3))))
     (shortdoc-section ((t (:family "Sans Serif"))))
     (show-paren-match ((t (:background "steelblue3"))))
     (show-paren-match-expression ((t (:background "steelblue3"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (shr-abbreviation ((t (:bold t :weight bold :underline (:style wave)))))
     (shr-h1 ((t (:bold t :weight bold :height 1.3))))
     (shr-h2 ((t (:bold t :weight bold))))
     (shr-h3 ((t (:italic t :slant italic))))
     (shr-h4 ((t (nil))))
     (shr-h5 ((t (nil))))
     (shr-h6 ((t (nil))))
     (shr-link ((t (:underline t :foreground "cyan1"))))
     (shr-selected-link ((t (:foreground "cyan1" :underline t :background "red"))))
     (shr-strike-through ((t (:strike-through t))))
     (smerge-base ((t (:extend t :background "#888833"))))
     (smerge-lower ((t (:extend t :background "#335533"))))
     (smerge-markers ((t (:extend t :background "grey30"))))
     (smerge-refined-added ((t (:background "#22aa22"))))
     (smerge-refined-changed ((t (nil))))
     (smerge-refined-removed ((t (:background "#aa2222"))))
     (smerge-upper ((t (:extend t :background "#553333"))))
     (success ((t (:bold t :foreground "Green1" :weight bold))))
     (tab-bar ((t (:family "Sans Serif" :background "grey85" :foreground "black"))))
     (tab-bar-tab ((t (:foreground "black" :background "grey85" :family "Sans Serif" :box (:line-width 1 :style released-button)))))
     (tab-bar-tab-group-current ((t (:bold t :box (:line-width 1 :style released-button) :family "Sans Serif" :background "grey85" :foreground "black" :box nil :weight bold))))
     (tab-bar-tab-group-inactive ((t (:foreground "grey70"))))
     (tab-bar-tab-inactive ((t (:box (:line-width 1 :style released-button) :family "Sans Serif" :foreground "black" :background "grey75"))))
     (tab-bar-tab-ungrouped ((t (:foreground "grey70"))))
     (tab-line ((t (:family "Sans Serif" :background "grey85" :foreground "black" :height 0.9))))
     (table-cell ((t (:background "blue1" :foreground "gray90" :inverse-video nil))))
     (tabulated-list-fake-header ((t (:bold t :overline t :underline t :weight bold))))
     (tool-bar ((t (:foreground "black" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (transient-active-infix ((t (:background "SkyBlue4" :extend t))))
     (transient-amaranth ((t (:foreground "#E52B50"))))
     (transient-argument ((t (:bold t :foreground "Pink" :weight bold))))
     (transient-blue ((t (:foreground "blue"))))
     (transient-disabled-suffix ((t (:bold t :background "red" :foreground "black" :weight bold))))
     (transient-enabled-suffix ((t (:bold t :background "green" :foreground "black" :weight bold))))
     (transient-heading ((t (:foreground "Cyan1"))))
     (transient-higher-level ((t (:underline t))))
     (transient-inactive-argument ((t (:foreground "grey70"))))
     (transient-inactive-value ((t (:foreground "grey70"))))
     (transient-inapt-suffix ((t (:italic t :foreground "grey70" :slant italic))))
     (transient-key ((t (:foreground "LightSteelBlue"))))
     (transient-mismatched-key ((t (:underline t))))
     (transient-nonstandard-key ((t (:underline t))))
     (transient-pink ((t (:foreground "#FF6EB4"))))
     (transient-purple ((t (:foreground "#a020f0"))))
     (transient-red ((t (:foreground "red"))))
     (transient-separator ((t (:extend t :background "grey30"))))
     (transient-teal ((t (:foreground "#367588"))))
     (transient-unreachable ((t (:foreground "grey70"))))
     (transient-unreachable-key ((t (:foreground "LightSteelBlue"))))
     (transient-value ((t (:foreground "LightSalmon"))))
     (treemacs-async-loading-face ((t (:foreground "chocolate1" :height 0.8))))
     (treemacs-directory-collapsed-face ((t (:foreground "LightSkyBlue"))))
     (treemacs-directory-face ((t (:foreground "LightSkyBlue"))))
     (treemacs-file-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (treemacs-fringe-indicator-face ((t (:foreground "white"))))
     (treemacs-git-added-face ((t (:foreground "PaleGreen"))))
     (treemacs-git-commit-diff-face ((t (:foreground "chocolate1"))))
     (treemacs-git-conflict-face ((t (:bold t :weight bold :foreground "Pink"))))
     (treemacs-git-ignored-face ((t (:foreground "chocolate1"))))
     (treemacs-git-modified-face ((t (:foreground "LightGoldenrod"))))
     (treemacs-git-renamed-face ((t (:foreground "LightSalmon"))))
     (treemacs-git-unmodified-face ((t (:extend nil :stipple nil :background "unspecified-bg" :foreground "unspecified-fg" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "default" :family "default" :height 1))))
     (treemacs-git-untracked-face ((t (:foreground "LightSalmon"))))
     (treemacs-header-button-face ((t (:foreground "Cyan1"))))
     (treemacs-help-column-face ((t (:foreground "Cyan1" :underline t))))
     (treemacs-help-title-face ((t (:foreground "Aquamarine"))))
     (treemacs-hl-line-face ((t (:extend t :background "darkolivegreen"))))
     (treemacs-marked-file-face ((t (:bold t :background "#AB3737" :foreground "#F0C674" :weight bold))))
     (treemacs-on-failure-pulse-face ((t (:extend t :background "#ab3737" :foreground "#111111"))))
     (treemacs-on-success-pulse-face ((t (:extend t :background "#669966" :foreground "#111111"))))
     (treemacs-peek-mode-indicator-face ((t (:background "#669966"))))
     (treemacs-root-face ((t (:bold t :foreground "Aquamarine" :underline t :weight bold :height 1.2))))
     (treemacs-root-remote-disconnected-face ((t (:bold t :weight bold :foreground "DarkOrange"))))
     (treemacs-root-remote-face ((t (:foreground "LightSkyBlue"))))
     (treemacs-root-remote-unreadable-face ((t (:bold t :strike-through t :foreground "Aquamarine" :underline t :weight bold :height 1.2))))
     (treemacs-root-unreadable-face ((t (:bold t :weight bold :underline t :foreground "Aquamarine" :strike-through t :height 1.2))))
     (treemacs-tags-face ((t (:foreground "LightSteelBlue"))))
     (treemacs-term-node-face ((t (:foreground "LightSalmon"))))
     (treemacs-window-background-face ((t (:family "default" :foundry "default" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "unspecified-fg" :background "unspecified-bg" :stipple nil :extend nil :height 1))))
     (tty-menu-disabled-face ((t (:background "blue" :foreground "lightgray"))))
     (tty-menu-enabled-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold))))
     (tty-menu-selected-face ((t (:background "red"))))
     (underline ((t (:bold t :weight bold))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vc-conflict-state ((t (nil))))
     (vc-edited-state ((t (nil))))
     (vc-locally-added-state ((t (nil))))
     (vc-locked-state ((t (nil))))
     (vc-missing-state ((t (nil))))
     (vc-needs-update-state ((t (nil))))
     (vc-removed-state ((t (nil))))
     (vc-state-base ((t (nil))))
     (vc-up-to-date-state ((t (nil))))
     (vertical-border ((t (:weight light :box (:line-width -1 :color "grey40" :style nil) :foreground "grey80" :background "grey30"))))
     (warning ((t (:bold t :foreground "DarkOrange" :weight bold))))
     (wgrep-delete-face ((t (:background "SlateGray1" :foreground "pink"))))
     (wgrep-done-face ((t (:foreground "LightSkyBlue"))))
     (wgrep-face ((t (:background "SlateGray1" :foreground "Black"))))
     (wgrep-file-face ((t (:background "gray30" :foreground "white"))))
     (wgrep-reject-face ((t (:bold t :foreground "HotPink" :weight bold))))
     (which-func ((t (:foreground "Blue1"))))
     (which-key-command-description-face ((t (:foreground "LightSkyBlue"))))
     (which-key-docstring-face ((t (:foreground "chocolate1"))))
     (which-key-group-description-face ((t (:foreground "Cyan1"))))
     (which-key-highlighted-command-face ((t (:foreground "LightSkyBlue" :underline t))))
     (which-key-key-face ((t (:foreground "Aquamarine"))))
     (which-key-local-map-description-face ((t (:foreground "LightSkyBlue"))))
     (which-key-note-face ((t (:foreground "chocolate1"))))
     (which-key-separator-face ((t (:foreground "chocolate1"))))
     (which-key-special-key-face ((t (:bold t :background "Aquamarine" :weight bold))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:extend t :background "yellow3" :foreground "black"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-single-line-field ((t (:background "green3" :foreground "black"))))
     (window-divider ((t (:foreground "gray60"))))
     (window-divider-first-pixel ((t (:foreground "gray80"))))
     (window-divider-last-pixel ((t (:foreground "gray40"))))
     (xref-file-header ((t (:bold t :foreground "Green1" :weight bold))))
     (xref-line-number ((t (:foreground "Cyan1"))))
     (xref-match ((t (:background "RoyalBlue3"))))
     (yas--field-debug-face ((t (nil))))
     (yas-field-highlight-face ((t (:background "blue3" :extend t)))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))